"cloud.nibalizer.com.":
  - name: "staypuft.cloud.nibalizer.com."
    type: "A"
    data: "15.126.240.46"
  - name: "wob.cloud.nibalizer.com."
    type: "A"
    data: "15.126.129.203"

"cloud.nibalizer.com.":
  - name: "staypuft.cloud.nibalizer.com."
    type: "A"
    data: "15.126.240.46"
  - name: "wob.cloud.nibalizer.com."
    type: "A"
    data: "15.126.129.203"
  - name: "derp999.cloud.nibalizer.com."
    type: "A"
    data: "15.126.129.202"
  - name: "lasers9999.cloud.nibalizer.com."
    type: "CNAME"
    data: "derp999.cloud.nibalizer.com."
  - name: "beaker.cloud.nibalizer.com."
    type: "CNAME"
    data: "derp999.cloud.nibalizer.com."

